Development/garage doors
GrimWorld-40-000/Vehicles-of-Grimworld pull request #4
Opened 2023-10-03 13:10 UTC by LazyEpsilon

Will want to update the labels and descriptions of stuff and it needs a balancing pass, other than that should be good to go.

2023-10-03 14:21 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageAutodoor.cs
> +            switch (_doorState)
Could be a single yield return new Command_Action with switched logic within the .action delegate.

2023-10-03 14:53 UTC, RealTelefonmast requested changes

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +    public class GarageDoor : Building
Curious, is this how other vehicle mods do it? Vanilla Building_Door has hardcoded ai and path logic that is based on that class, making a completely custom door could ignore such logic. 
Just for clarification.

2023-10-03 14:53 UTC, RealTelefonmast commented on 1.4/Defs/WorkGiverDefs/WorkGivers.xml
> +    <defName>GW_OpenGarages</defName>
Could make use of requiredCapacities to ensure that only pawns capable of manipulation can open and close garages

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Statics/ExtensionMethods.cs
> +        public static float Map(this float value, float minSource, float maxSource, float minTarget, float maxTarget) =>
personal preference, methods as lambdas are generally less maintainable, especially for extensions

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Statics/Vehicles_of_Grimworld.cs
> +            new Harmony($"{nameof(Vehicles_of_Grimworld)}.Mod").PatchAll();
While this works, I think its preferable to instantiate it in a class extending Mod (like VOGMod or something) and then save it in a field, unsure if the current way may have side-effects.

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Vehicles_of_Grimworld.csproj
> +    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(SolutionDir)..\..\1.4\Assemblies\$(ProjectName).dll&quot;" />
Could simply change the output directory to the Assemblies folder, unsure if that may be a naive approach of mine though.

```
    <OutputPath>..\..\1.4\Assemblies</OutputPath>
```

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/DoorState.cs
> +        closed,
Personally prefer and always use PascalCase enums

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +    public class GarageDoor : Building
I just realized this doesnt exactly act like a door in the first place, and simply blocks the "door space" with a blocking object. I suppose AI and pathing is irrelevant than as these are manually controlled by default.

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +                        yield return new Command_Action
Once again, personal preference, but technically doable with a single yield return, but works all the same.

2023-10-03 14:53 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +        private void Open()
Another approach could be to always have a "garage door" building/entity as a foundation which only spawns a blocker ontop of it when its closed, thus there wouldnt be a need to spawn/respawn entire buildings and re-attach logic.
This would require entire rewriting though, so just a thought.

2023-10-03 15:00 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +        private void Open()
You know, that would be a much better way of writing this that would solve a lot of problems, an unselectable blocker sat over the top when the door is "closed", would also solve a slight probem with the electricity comp re-connecting every time you open or close the auto-door.

Downsides of taking inspiration from something else at it's finest here, if I get some time I might re-write it to work this way.

2023-10-03 15:01 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/DoorState.cs
> +        closed,
Yup, not sure why I didn't to be honest.

2023-10-03 15:02 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Vehicles_of_Grimworld.csproj
> +    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(SolutionDir)..\..\1.4\Assemblies\$(ProjectName).dll&quot;" />
Yeah I'd agree that one can do that, I was just trying to avoid needing to turn off outputting PDBs and I wanted to safeguard against any possible future dependencies dumping their output into the bin folder and getting copied so I thought something more targetted would be better.

2023-10-03 15:03 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Statics/ExtensionMethods.cs
> +        public static float Map(this float value, float minSource, float maxSource, float minTarget, float maxTarget) =>
Out of curiosity what makes you say they're less maintainable?

2023-10-03 15:03 UTC, LazyEpsilon commented on 1.4/Defs/WorkGiverDefs/WorkGivers.xml
> +    <defName>GW_OpenGarages</defName>
That'd make good sense.

2023-10-03 15:07 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Statics/ExtensionMethods.cs
> +        public static float Map(this float value, float minSource, float maxSource, float minTarget, float maxTarget) =>
Just on first glance it takes longer to read it as a whole line when the lambda points to a long statement, especially with other methods joining that extensions class it might become hard to oversee, might just be me

2023-10-03 15:11 UTC, RealTelefonmast commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +        private void Open()
I have code references for such behaviour on a "laser fence" building i made, spawns invisible blockers when the fence is active, if you want.

2023-10-03 22:59 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +        private void Open()
Yep that'd be good if you don't mind, I think I'll put it in the TODO list , it'd definitely be a good re-write to do but this does work as intended currently.

2023-10-06 09:33 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Vehicles_of_Grimworld.csproj
> +    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(SolutionDir)..\..\1.4\Assemblies\$(ProjectName).dll&quot;" />
Ah the wiki just went on a bit about how rimworld is bad at dealing with PDBs and might just fall over because of it as it doesn't know what to do with them, but if that doesn't happen with an embedded PDB I'll do that.

I'm aware you can, I've already done that for both Krafs and Harmony, think I'm going to stick to my slightly funky way of doing it as I like the single DLL copy to assembly (also doesn't result in some random bin folder structure being present in the assemblies folder). If it ever causes problems I'll do it the normal way ^^

2023-10-06 09:41 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/GarageAutodoor.cs
> +            switch (_doorState)
I agree that one could write the code this way, however it would involve writing all the other properties on ternary conditional operators that would be checking for two things alongside needing an extra if statement to check if we're in the right state here anyway in order to not return an empty widget if we're not open or closed.

2023-10-06 09:42 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/GarageDoor.cs
> +                        yield return new Command_Action
My point is the same here as above.

2023-10-06 16:18 UTC, LazyEpsilon commented on Source/Vehicles_of_Grimworld/Buildings/GarageAutodoor.cs
> +            switch (_doorState)
Resolved!

2023-10-06 16:28 UTC, RealTelefonmast approved these changes

2023-10-06 16:29 UTC, merged